/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.CtrlFrmRegistrarDisco;

/**
 *
 * @author dicxie
 */
public class vistaRegistrarDisco extends javax.swing.JInternalFrame {
    public vistaMain vistaPrincipal;
    public vistaRegistrarDisco vistaDisco;
    
    /**
     * Creates new form ifrmRegritrarDisco
     */
    public vistaRegistrarDisco() {

        initComponents();
         AddControlles(new CtrlFrmRegistrarDisco(this));
    }
    public vistaRegistrarDisco(vistaMain frm){
        initComponents();
        CtrlFrmRegistrarDisco C = new CtrlFrmRegistrarDisco(this);
        C.formularioPrincipal = frm;
        AddControlles(C);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnRegistrarDisco = new javax.swing.JPanel();
        lblIdArtista = new javax.swing.JLabel();
        txtIdDisco = new javax.swing.JTextField();
        lblLanzamiento = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txttitulo = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtLanzamiento = new javax.swing.JSpinner();
        btnNuevoDisco = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnVistaArtista = new javax.swing.JPanel();
        spAritsta = new javax.swing.JScrollPane();
        lstArtista = new javax.swing.JList<modelo.Artista>();
        btnAgregarArtista = new javax.swing.JButton();
        btnEliminarArtista = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbArtista = new javax.swing.JTable();
        btnNuevoArtista = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbDisco = new javax.swing.JTable();

        setClosable(true);

        pnRegistrarDisco.setBorder(javax.swing.BorderFactory.createTitledBorder("Infomación de Disco Musicales"));

        lblIdArtista.setText("Código disco:");

        txtIdDisco.setEditable(false);
        txtIdDisco.setEnabled(false);
        txtIdDisco.setFocusable(false);

        lblLanzamiento.setText("Año lanzamiento :");

        jScrollPane1.setAutoscrolls(true);

        txttitulo.setColumns(20);
        txttitulo.setLineWrap(true);
        txttitulo.setRows(5);
        txttitulo.setEnabled(false);
        txttitulo.setLineWrap(true);
        jScrollPane1.setViewportView(txttitulo);

        jLabel3.setText("Titulo:");

        txtLanzamiento.setEnabled(false);

        btnNuevoDisco.setText("Nuevo");
        btnNuevoDisco.setActionCommand("NuevoDisco");

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);

        javax.swing.GroupLayout pnRegistrarDiscoLayout = new javax.swing.GroupLayout(pnRegistrarDisco);
        pnRegistrarDisco.setLayout(pnRegistrarDiscoLayout);
        pnRegistrarDiscoLayout.setHorizontalGroup(
            pnRegistrarDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRegistrarDiscoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRegistrarDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdArtista)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnRegistrarDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(txtIdDisco))
                .addContainerGap())
            .addGroup(pnRegistrarDiscoLayout.createSequentialGroup()
                .addComponent(lblLanzamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnRegistrarDiscoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevoDisco))
        );
        pnRegistrarDiscoLayout.setVerticalGroup(
            pnRegistrarDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRegistrarDiscoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRegistrarDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdArtista)
                    .addComponent(txtIdDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnRegistrarDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnRegistrarDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLanzamiento)
                    .addComponent(txtLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnRegistrarDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoDisco)
                    .addComponent(btnEliminar)
                    .addComponent(btnCancelar))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pnVistaArtista.setBorder(javax.swing.BorderFactory.createTitledBorder("Interprete"));

        lstArtista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstArtista.setEnabled(false);
        spAritsta.setViewportView(lstArtista);

        btnAgregarArtista.setText("<<");
        btnAgregarArtista.setActionCommand("Agregar");
        btnAgregarArtista.setEnabled(false);
        btnAgregarArtista.setPreferredSize(new java.awt.Dimension(73, 22));

        btnEliminarArtista.setText("Eliminar");
        btnEliminarArtista.setActionCommand("EliminarArtista");
        btnEliminarArtista.setEnabled(false);

        tbArtista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Completo", "Nombre Artistico", "Nacionalidad "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbArtista.setEnabled(false);
        jScrollPane3.setViewportView(tbArtista);

        btnNuevoArtista.setText("Nuevo");
        btnNuevoArtista.setActionCommand("NuevoArtista");
        btnNuevoArtista.setEnabled(false);

        javax.swing.GroupLayout pnVistaArtistaLayout = new javax.swing.GroupLayout(pnVistaArtista);
        pnVistaArtista.setLayout(pnVistaArtistaLayout);
        pnVistaArtistaLayout.setHorizontalGroup(
            pnVistaArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVistaArtistaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spAritsta, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnVistaArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregarArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoArtista)
                    .addComponent(btnEliminarArtista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        pnVistaArtistaLayout.setVerticalGroup(
            pnVistaArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVistaArtistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnVistaArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnVistaArtistaLayout.createSequentialGroup()
                        .addComponent(btnAgregarArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevoArtista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarArtista))
                    .addComponent(spAritsta, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(344, 344, 344))
        );

        tbDisco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Disco", "Lanzamiento", "Artista"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDisco.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbDisco.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbDisco.setShowHorizontalLines(true);
        tbDisco.setShowVerticalLines(true);
        jScrollPane4.setViewportView(tbDisco);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnRegistrarDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnVistaArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnVistaArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnRegistrarDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void AddControlles(CtrlFrmRegistrarDisco C){
        
        this.addInternalFrameListener(C);
        this.btnAgregarArtista.addActionListener(C);
        btnEliminarArtista.addActionListener(C);
        btnEliminar.addActionListener(C);
        btnNuevoArtista.addActionListener(C);
        btnCancelar.addActionListener(C);
        btnAgregarArtista.addActionListener(C);
        btnNuevoDisco.addActionListener(C);
        tbDisco.getSelectionModel().addListSelectionListener(C);
        tbDisco.addMouseListener(C);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarArtista;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnEliminarArtista;
    public javax.swing.JButton btnNuevoArtista;
    public javax.swing.JButton btnNuevoDisco;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JLabel lblIdArtista;
    public javax.swing.JLabel lblLanzamiento;
    public javax.swing.JList lstArtista;
    private javax.swing.JPanel pnRegistrarDisco;
    private javax.swing.JPanel pnVistaArtista;
    public javax.swing.JScrollPane spAritsta;
    public javax.swing.JTable tbArtista;
    public javax.swing.JTable tbDisco;
    public javax.swing.JTextField txtIdDisco;
    public javax.swing.JSpinner txtLanzamiento;
    public javax.swing.JTextArea txttitulo;
    // End of variables declaration//GEN-END:variables

}
